// Maps Minecraft Bedrock APIs to their required modules
module.exports = {
    'world.getDimension': ['@minecraft/server'],
    'system.run': ['@minecraft/server'],
    'Entity.screen': ['@minecraft/server-ui'],
    'Player.spawn': ['@minecraft/server'],
    'Block.setType': ['@minecraft/server'],
    'Entity.addEffect': ['@minecraft/server'],
    'Entity.applyImpulse': ['@minecraft/server'],
    'Entity.applyKnockback': ['@minecraft/server'],
    'Entity.clearVelocity': ['@minecraft/server'],
    'Entity.extinguishFire': ['@minecraft/server'],
    'Entity.getBlockFromViewDirection': ['@minecraft/server'],
    'Entity.getDynamicProperty': ['@minecraft/server'],
    'Entity.getRotation': ['@minecraft/server'],
    'Entity.playAnimation': ['@minecraft/server'],
    'Entity.setDynamicProperty': ['@minecraft/server'],
    'Entity.setRotation': ['@minecraft/server'],
    'Entity.teleport': ['@minecraft/server'],
    'Entity.triggerEvent': ['@minecraft/server'],
    'Dimension.fillBlocks': ['@minecraft/server'],
    'Dimension.getBlock': ['@minecraft/server'],
    'Dimension.getEntities': ['@minecraft/server'],
    'Dimension.getPlayers': ['@minecraft/server'],
    'Dimension.runCommand': ['@minecraft/server'],
    'Dimension.spawnEntity': ['@minecraft/server'],
    'Dimension.spawnItem': ['@minecraft/server'],
    'Block.setPermutation': ['@minecraft/server'],
    'Block.setType': ['@minecraft/server'],
    'Block.getComponent': ['@minecraft/server'],
    'Block.getRedstonePower': ['@minecraft/server'],
    'Block.isWaterlogged': ['@minecraft/server'],
    'Block.isAir': ['@minecraft/server'],
    'Block.location': ['@minecraft/server'],
    'Block.permutation': ['@minecraft/server'],
    'Block.type': ['@minecraft/server'],
    'Block.above': ['@minecraft/server']
};